// <auto-generated/>
using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyVersionAttribute("0.0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.0.1")]
[assembly: AssemblyProductAttribute("Paydock.Net.Sdk")]
[assembly: AssemblyCompanyAttribute("Paydock")]
[assembly: AssemblyCopyrightAttribute("Copyright � Paydock 2017. Warning: This computer program is protected by copyright law and international treaties. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law.")]
[assembly: AssemblyTrademarkAttribute("Ibox is a registered trademark of Paydock.")]
[assembly: AssemblyConfigurationAttribute("Debug")]
[assembly: CLSCompliantAttribute(true)]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "0.0.0.1";
        internal const System.String AssemblyFileVersion = "0.0.0.1";
        internal const System.String AssemblyProduct = "Paydock.Net.Sdk";
        internal const System.String AssemblyCompany = "Paydock";
        internal const System.String AssemblyCopyright = "Copyright � Paydock 2017. Warning: This computer program is protected by copyright law and international treaties. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law.";
        internal const System.String AssemblyTrademark = "Ibox is a registered trademark of Paydock.";
        internal const System.String AssemblyConfiguration = "Debug";
        internal const System.Boolean CLSCompliant = true;
        internal const System.Boolean ComVisible = false;
    }
}
