<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netstandard1.2</TargetFramework>
    <ApplicationIcon />
    <OutputTypeEx>library</OutputTypeEx>
    <StartupObject />
    <RootNamespace>Paydock_dotnet_sdk</RootNamespace>
    <AssemblyVersion>1.3.20</AssemblyVersion>
    <FileVersion>1.3.20</FileVersion>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>PayDockOssKeyFile.snk</AssemblyOriginatorKeyFile>
    <AssemblyName>PaydockSdk.Core</AssemblyName>
    <PackageVersion>1.3.20</PackageVersion>
    <Version>1.3.20</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>Paydock .Net Standard SDK</Description>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
    <DebugSymbols>True</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Models\ChargeResponse.cs" />
    <Compile Include="Models\ChargeItemResponse.cs" />
    <Compile Include="Models\ChargeItemsResponse.cs" />
    <Compile Include="Models\ChargeRefundRequest.cs" />
    <Compile Include="Models\ChargeRefundResponse.cs" />
    <Compile Include="Models\ChargeRequest.cs" />
    <Compile Include="Models\ChargeRequestBase.cs" />
    <Compile Include="Models\ChargeRequestStripeConnect.cs" />
    <Compile Include="Models\WalletResponse.cs" />
    <Compile Include="Models\WalletAmountDetails.cs" />
    <Compile Include="Models\WalletCardAcceptor.cs" />
    <Compile Include="Models\WalletChargeItem.cs" />
    <Compile Include="Models\ChargeSearchRequest.cs" />
    <Compile Include="Models\TransactionResponse.cs" />
    <Compile Include="Models\Customer.cs" />
    <Compile Include="Models\CustomerItemResponse.cs" />
    <Compile Include="Models\CustomerItemsResponse.cs" />
    <Compile Include="Models\CustomerRequest.cs" />
    <Compile Include="Models\CustomerResponse.cs" />
    <Compile Include="Models\CustomerSearchRequest.cs" />
    <Compile Include="Models\CustomerUpdateRequest.cs" />
    <Compile Include="Models\ErrorResponse.cs" />
    <Compile Include="Models\ErrorResponseBase.cs" />
    <Compile Include="Models\ExternalCheckoutRequest.cs" />
    <Compile Include="Models\ExternalCheckoutResponse.cs" />
    <Compile Include="Models\GatewayData.cs" />
    <Compile Include="Models\GatewayItemResponse.cs" />
    <Compile Include="Models\GatewayItemsResponse.cs" />
    <Compile Include="Models\GatewayRequest.cs" />
    <Compile Include="Models\GatewayResponse.cs" />
    <Compile Include="Models\GatewayUpdateRequest.cs" />
    <Compile Include="Models\NotificationLogRequest.cs" />
    <Compile Include="Models\NotificationLogResponse.cs" />
    <Compile Include="Models\NotificationLogsResponse.cs" />
    <Compile Include="Models\NotificationTemplateItemsResponse.cs" />
    <Compile Include="Models\NotificationTemplateRequest.cs" />
    <Compile Include="Models\NotificationTemplateResponse.cs" />
    <Compile Include="Models\NotificationTemplateUpdateRequest.cs" />
    <Compile Include="Models\NotificationTriggerData.cs" />
    <Compile Include="Models\NotificationTriggerItemsResponse.cs" />
    <Compile Include="Models\NotificationTriggerRequest.cs" />
    <Compile Include="Models\NotificationTriggerResponse.cs" />
    <Compile Include="Models\PaymentSource.cs" />
    <Compile Include="Models\ThreeDSecure.cs" />
    <Compile Include="Models\TransactionThreeDSecure.cs" />
    <Compile Include="Models\FraudData.cs" />
    <Compile Include="Models\FraudBase.cs" />
    <Compile Include="Models\ShippingData.cs" />
    <Compile Include="Models\FraudResponse.cs" />
    <Compile Include="Models\Response.cs" />
    <Compile Include="Models\ResponseException.cs" />
    <Compile Include="Models\SubscriptionItemResponse.cs" />
    <Compile Include="Models\SubscriptionItemsResponse.cs" />
    <Compile Include="Models\SubscriptionRequest.cs" />
    <Compile Include="Models\SubscriptionResponse.cs" />
    <Compile Include="Models\SubscriptionSchedule.cs" />
    <Compile Include="Models\SubscriptionSearchRequest.cs" />
    <Compile Include="Models\SubscriptionUpdateRequest.cs" />
    <Compile Include="Models\TokenRequest.cs" />
    <Compile Include="Models\TokenResponse.cs" />
    <Compile Include="Models\VaultItemsResponse.cs" />
    <Compile Include="Models\VaultRequest.cs" />
    <Compile Include="Models\VaultResponse.cs" />
    <Compile Include="Models\VaultType.cs" />
    <Compile Include="Models\Webhooks\CardExpiration.cs" />
    <Compile Include="Models\Webhooks\SubscriptionWebhook.cs" />
    <Compile Include="Models\Webhooks\TransactionWebhook.cs" />
    <Compile Include="Services\Config.cs" />
    <Compile Include="Tools\RequiresConfigAttribute.cs" />
    <Compile Include="Tools\ResponseExceptionFactory.cs" />
    <Compile Include="Tools\UrlExtensionMethods.cs" />
    <None Include="..\README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
    <PackageReference Include="System.ValueTuple" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\Webhooks\" />
  </ItemGroup>

</Project>
